version: "3.9"
services:
  prometheus:
    image: "prom/prometheus"
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - '/home/kodhi/Downloads/petshop/composetest/prometheuspet.yml:/etc/prometheus/prometheus.yml'
      - '/home/kodhi/Downloads/petshop/composetest/prometheuspet.rules.yml:/etc/prometheus/prometheuspet.rules.yml'
  node_exporter:
    image: "prom/node-exporter"
    container_name: node_exporter
    ports:
      - "9100:9100"
  petshop:
    image: "harbor.sflabs.com.br/processo/petshop"
    container_name: petshop
    ports:
      - "4000:3000"
  grafana:
    image: "grafana/grafana"
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - '/home/kodhi/Downloads/petshop/composetest/grafana.ini:/etc/grafana/grafana.ini'
      - '/home/kodhi/Downloads/petshop/composetest/data:/var/lib/grafana'
    user: "$UID:$GID"